const customclasses = require("../../database/models").customclasses;
const validation = require("../../database/validation");
const { update } = require("../../service/webSocket");
const router = require("express").Router();

router.get("/", async (req, res) => {
  try {
    const [records, field] = await customclasses.findAll();
    const { labels, schemas } = await customclasses.getSchema();
    res.send({
      success: true,
      data: { data: records, labels: labels, schemas: schemas },
    });
  } catch (error) {
    res.status(500).send({ success: false, message: "伺服器發生錯誤" });
  }
});

router.post("/", async (req, res) => {
  const { item, type } = req.body;
  const data = {
    item,
    type,
  };

  let { error } = validation.customclassesValidation(data);

  if (error) {
    return res.status(403).send({ success: false, message: error.details[0].message });
  }

  try {
    const [records, field] = await customclasses.insertOne(data);
    update(customclasses.tableName);
    res.send({ success: true, data: records });
  } catch (error) {
    res.status(500).send({ success: false, message: "伺服器發生錯誤" });
  }
});

router.put("/", async (req, res) => {
  const { item, type } = req.body;
  const data = {
    item,
    type,
  };

  let { error } = validation.customclassesValidation(data);

  if (error) {
    return res.status(403).send({ success: false, message: error.details[0].message });
  }

  try {
    const [records, field] = await customclasses.updateOne(data, ["item"]);
    update(customclasses.tableName);
    res.send({ success: true, data: records });
  } catch (error) {
    res.status(500).send({ success: false, message: "伺服器發生錯誤" });
  }
});

router.delete("/", async (req, res) => {
  const { item, type } = req.body;
  const data = {
    item,
    type,
  };

  try {
    const [records, field] = await customclasses.deleteOne(data, ["item"]);
    update(customclasses.tableName);
    res.send({
      success: true,
      data: records,
    });
  } catch (error) {
    res.status(500).send({ success: false, message: "伺服器發生錯誤" });
  }
});

module.exports = router;
